<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>GocDeployManager.UI</RootNamespace>
    <AssemblyName>GocDeployManager</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="NLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.102.2" />
    <PackageReference Include="PdfSharp" Version="1.50.5147" />
    <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GocDeployManager.Common\GocDeployManager.Common.csproj" />
    <ProjectReference Include="..\GocDeployManager.Domain\GocDeployManager.Domain.csproj" />
    <ProjectReference Include="..\GocDeployManager.Application\GocDeployManager.Application.csproj" />
    <ProjectReference Include="..\GocDeployManager.Infrastructure\GocDeployManager.Infrastructure.csproj" />
    <ProjectReference Include="..\GocDeployManager.Services\GocDeployManager.Services.csproj" />
  </ItemGroup>

</Project>
